### PR TITLE
Add setUpAsync() and tearDownAsync()

### PR DESCRIPTION
**Pull request by trowski**
As requested by @prolic, this PR adds async versions of `setUp()` and `tearDown()`, aptly named `setUpAsync()` and `tearDownAsync()`.

### CODE REVIEW

**Comment by trowski** [comment]
Question: Should `setUpAsync()` and `tearDownAsync()` require returning a promise, or should we use `Amp\call()`?

**Review by prolic — APPROVED** [review]

**Comment by prolic** [comment]
> Question: Should `setUpAsync()` and `tearDownAsync()` require returning a promise, or should we use `Amp\call()`?

I don't have any preference here.

**Comment by enumag** [comment]
Neither do I.

**Comment by prolic** [comment]
ping @trowski @kelunik

**Comment by enumag** [comment]
With phpunit-util the tests can just yield right? So for consistency the same should be allowed for setUpAsync and tearDownAsync. So I'm leaning towards using call.

**Comment by prolic** [comment]
perfect, merge and release? :+1:

**Review by kelunik — APPROVED** [review]

**Pull request merged**
