### PR TITLE
[2.x] Fix implicitly nullable parameter for PHP 8.4 compatibility

### PR DESCRIPTION
**Pull request by GromNaN**
PHP 8.4 deprecates implicit nullable parameter. This fix is for the branch 2.x. There is no issue on branch 3.x.

### CODE REVIEW

**Comment by Bilge** [comment]
That's epic, dude, but what makes you think 2.x is supposed to support 8.4?

**Review by kelunik — APPROVED** [review]

**Comment by kelunik** [comment]
@Bilge What makes you think it's not?

**Comment by GromNaN** [comment]
Thanks @kelunik. 

> That's epic, dude, but what makes you think 2.x is supposed to support 8.4?

vimeo/psalm uses this library in version 2. No doubt there will be a project to update, but for the moment I'm concentrating on PHP 8.4 compatibility.

**Comment by kelunik** [comment]
Tagged as v2.0.1: https://github.com/amphp/phpunit-util/releases/tag/v2.0.1

**Comment by Bilge** [comment]
> @Bilge What makes you think it's not?

Because coroutines are a concluded experiment and anyone on 8.1 should be using fibers.

**Pull request merged**
